# Docker Compose V3

version: '3'

services:

  wordpressdb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
    networks:
      - wordpressnet
    deploy:
      mode: replicated
      replicas: 1
      labels: [side=backend]

  wordpress:
    depends_on:
      - wordpressdb
    image: wordpress:latest
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: wordpressdb:3306
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
     - wordpressnet
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      labels: [side=frontend]

  # viz:
  #   depends_on:
  #   image: manomarks/visualizer
  #   ports:
  #     - "8080:8080"
  #   networks:
  #    - wordpressnet
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   deploy:
  #     placement:
  #       constraints: [node.role == manager]
  #     labels: [kind=viz]

networks:
  wordpressnet:
    driver: overlay
